app:
 message: THIS IS MESSAGE VALUE which is from CONFIG_CLIENT/dev/config-client-dev.ymlakjsfd;jas;fj;lkjasfd;lkj;lkasfjd;kljas;fkdlj;lkjas;klj;klj;kljlk;j
 key: this is key which is from CONFIG_CLIENT/dev/config-client-dev===================================================
